git clone git+ssh://tjyrinki@git.gnome.org/git/accerciser.git
git clone git+ssh://tjyrinki@git.gnome.org/git/aisleriot.git
git clone git+ssh://tjyrinki@git.gnome.org/git/alacarte.git
git clone git+ssh://tjyrinki@git.gnome.org/git/anjuta.git
git clone git+ssh://tjyrinki@git.gnome.org/git/at-spi2-atk.git
git clone git+ssh://tjyrinki@git.gnome.org/git/at-spi2-core.git
git clone git+ssh://tjyrinki@git.gnome.org/git/atk.git
git clone git+ssh://tjyrinki@git.gnome.org/git/baobab.git
git clone git+ssh://tjyrinki@git.gnome.org/git/brasero.git
git clone git+ssh://tjyrinki@git.gnome.org/git/caribou.git
git clone git+ssh://tjyrinki@git.gnome.org/git/cheese.git
git clone git+ssh://tjyrinki@git.gnome.org/git/clutter.git
git clone git+ssh://tjyrinki@git.gnome.org/git/cogl.git
git clone git+ssh://tjyrinki@git.gnome.org/git/devhelp.git
git clone git+ssh://tjyrinki@git.gnome.org/git/empathy.git
git clone git+ssh://tjyrinki@git.gnome.org/git/eog.git
git clone git+ssh://tjyrinki@git.gnome.org/git/epiphany.git
git clone git+ssh://tjyrinki@git.gnome.org/git/evince.git
git clone git+ssh://tjyrinki@git.gnome.org/git/evolution.git
git clone git+ssh://tjyrinki@git.gnome.org/git/evolution-data-server.git
git clone git+ssh://tjyrinki@git.gnome.org/git/file-roller.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gcalctool.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gconf.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gconf-editor.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gdk-pixbuf.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gdl.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gdm.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gedit.git
git clone git+ssh://tjyrinki@git.gnome.org/git/glade.git
git clone git+ssh://tjyrinki@git.gnome.org/git/glib.git
git clone git+ssh://tjyrinki@git.gnome.org/git/glib-networking.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gnome-backgrounds.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gnome-bluetooth.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gnome-boxes.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gnome-contacts.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gnome-control-center.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gnome-desktop.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gnome-dictionary.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gnome-disk-utility.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gnome-doc-utils.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gnome-documents.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gnome-font-viewer.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gnome-games.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gnome-icon-theme.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gnome-keyring.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gnome-menus.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gnome-nettool.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gnome-online-accounts.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gnome-packagekit.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gnome-panel.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gnome-power-manager.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gnome-screensaver.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gnome-screenshot.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gnome-search-tool.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gnome-session.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gnome-settings-daemon.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gnome-shell.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gnome-shell-extensions.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gnome-system-log.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gnome-system-monitor.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gnome-terminal.git gnome-terminal.gnome-3-4
git clone git+ssh://tjyrinki@git.gnome.org/git/gnome-themes-standard.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gnome-user-share.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gnome-video-effects.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gtkhtml.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gtksourceview.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gucharmap.git
git clone git+ssh://tjyrinki@git.gnome.org/git/gvfs.git
git clone git+ssh://tjyrinki@git.gnome.org/git/hamster-applet.git
git clone git+ssh://tjyrinki@git.gnome.org/git/libgdata.git
git clone git+ssh://tjyrinki@git.gnome.org/git/libgnome-keyring.git
git clone git+ssh://tjyrinki@git.gnome.org/git/libgnome-media-profiles.git
git clone git+ssh://tjyrinki@git.gnome.org/git/libgnomekbd.git
git clone git+ssh://tjyrinki@git.gnome.org/git/libgtop.git
git clone git+ssh://tjyrinki@git.gnome.org/git/libgweather.git
git clone git+ssh://tjyrinki@git.gnome.org/git/libpeas.git
git clone git+ssh://tjyrinki@git.gnome.org/git/libwnck.git
git clone git+ssh://tjyrinki@git.gnome.org/git/locations.git
git clone git+ssh://tjyrinki@git.gnome.org/git/metacity.git
git clone git+ssh://tjyrinki@git.gnome.org/git/mousetweaks.git
git clone git+ssh://tjyrinki@git.gnome.org/git/mutter.git
git clone git+ssh://tjyrinki@git.gnome.org/git/nautilus.git
git clone git+ssh://tjyrinki@git.gnome.org/git/nautilus-sendto.git
git clone git+ssh://tjyrinki@git.gnome.org/git/network-manager-applet.git
git clone git+ssh://tjyrinki@git.gnome.org/git/notification-daemon.git
git clone git+ssh://tjyrinki@git.gnome.org/git/orca.git
git clone git+ssh://tjyrinki@git.gnome.org/git/seahorse.git
git clone git+ssh://tjyrinki@git.gnome.org/git/seahorse-plugins.git
git clone git+ssh://tjyrinki@git.gnome.org/git/sushi.git
git clone git+ssh://tjyrinki@git.gnome.org/git/tomboy.git
git clone git+ssh://tjyrinki@git.gnome.org/git/totem.git
git clone git+ssh://tjyrinki@git.gnome.org/git/totem-pl-parser.git
git clone git+ssh://tjyrinki@git.gnome.org/git/vinagre.git
git clone git+ssh://tjyrinki@git.gnome.org/git/vino.git
git clone git+ssh://tjyrinki@git.gnome.org/git/vte.git
git clone git+ssh://tjyrinki@git.gnome.org/git/yelp.git
git clone git+ssh://tjyrinki@git.gnome.org/git/yelp-xsl.git
git clone git+ssh://tjyrinki@git.gnome.org/git/zenity.git

